export const students = [
  {
    id: "1",
    name: "Ajay Rathod",
    image: "https://i.pravatar.cc?u=fak@pravatar.com",
    class_room: "class1",
    tag: "tag1",
  },
  {
    id: "2",
    name: "Lex Fenwick",
    image: "https://i.pravatar.cc?u=fae@pravatar.com",
    class_room: "class2",
    tag: "tag2",
  },
  {
    id: "3",
    name: "Lisa Adams",
    image: "https://i.pravatar.cc?u=ake@pravatar.com",
    class_room: "class2",
    tag: "tag2",
  },
  {
    id: "4",
    name: "Chaitanya Bhave",
    image: "https://i.pravatar.cc?u=fake@prvatar.com",
    class_room: "class1",
    tag: "tag1",
  },
  {
    id: "5",
    name: "Devi Vampati",
    image: "https://i.pravatar.cc?u=fake@pavatar.com",
    class_room: "class2",
    tag: "tag1",
  },
  {
    id: "6",
    name: "Jessica Lima",
    image: "https://i.pravatar.cc?u=fake@pravaar.com",
    class_room: "class1",
    tag: "tag2",
  },
  {
    id: "7",
    name: "Kimberly Dixon",
    image: "https://i.pravatar.cc?u=fake@praatar.com",
    class_room: "class2",
    tag: "tag2",
  },
  {
    id: "8",
    name: "Nichole Adams",
    image: "https://i.pravatar.cc?u=bold@pravatar.com",
    class_room: "class1",
    tag: "tag1",
  },
  {
    id: "9",
    name: "Sree Vyshnavi Bathini",
    image: "https://i.pravatar.cc?u=fa@pravatar.com",
    class_room: "class2",
    tag: "tag2",
  },
  {
    id: "10",
    name: "Aria KC",
    image: "https://i.pravatar.cc?u=fake@pratar.com",
    class_room: "class1",
    tag: "tag1",
  },
  {
    id: "11",
    name: "Ashwat Mulgaonkar",
    image: "https://i.pravatar.cc?u=fake@prar.com",
    class_room: "class2",
    tag: "tag1",
  },
  {
    id: "12",
    name: "Atraye Rawal",
    image: "https://i.pravatar.cc?u=fake@prtar.com",
    class_room: "class2",
    tag: "tag1",
  },
];
